services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000" # Porta 4000 no host mapeada para a 3000 no container
    networks:
      - ola-metrics-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090" # Porta 9090 para acessar o Prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - ola-metrics-network

  grafana:
    image: grafana/grafana
    ports:
      - "4001:3000" # Porta 4001 no host mapeada para a 3000 do Grafana
    networks:
      - ola-metrics-network

networks:
  ola-metrics-network:
    driver: bridge